FROM php:8.0-apache

# Install and enable xdebug
RUN pecl install xdebug && docker-php-ext-enable xdebug

# npm is required to init some fykos plugins
RUN apt-get update && apt-get install -y npm

# Following packages are required for some php addons
RUN apt-get install -y zlib1g-dev libpng-dev sqlite3

# Install and enable extensions required by some plugins
RUN docker-php-ext-install gd mysqli \
    && docker-php-ext-enable gd mysqli

# Fix ownership
RUN chown -R www-data:www-data /var/www/html && chmod -R 0770 /var/www/html

# Apply changes & restart apache service
RUN a2enmod rewrite && service apache2 restart